apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: text-to-image-app
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: text-to-image-app
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 80
