apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: text-to-image-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: text-to-image
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 50
