apiVersion: apps/v1
kind: Deployment
metadata:
  name: text-to-image-app
  namespace: default  # Add this line to specify the namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: text-to-image-app
  template:
    metadata:
      labels:
        app: text-to-image-app
    spec:
      containers:
      - name: text-to-image-app
        image: your-image-name:tag  # Replace with your actual image
        ports:
        - containerPort: 8080
