apiVersion: apps/v1
kind: Deployment
metadata:
  name: text-to-image-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: text-to-image-app
  template:
    metadata:
      labels:
        app: text-to-image-app
    spec:
      containers:
      - name: text-to-image-app
        image: your-docker-registry/text-to-image-app:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
