apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: text-to-image-app
  namespace: flux-system
spec:
  interval: 5m
  path: "./clusters/my-cluster/text-to-image-app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: text-to-image-app
  targetNamespace: text-to-image-app
